name: Setup CI/CD
description: Configures various useful things for my personal CI/CD workflows.

inputs:
  python-version:
    description: Python version to install.
    required: false
  python-packages:
    description: Python packages to install. Requires python-version.
    required: false
  node-version:
    description: Node version to install.
    required: false
  npm-packages:
    description: NPM packages to install. Requires node-version.
    required: false
  role-to-assume:
    description: AWS IAM role to assume when setting up AWS credentials. Enter "default" to use the global GitHub Actions CDK role.
    required: false
  aws-region:
    description: AWS region.
    required: false
    default: us-east-1

runs:
  using: composite
  steps:
    # Python

    - if: inputs.python-version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
    
    - if: inputs.python-version
      uses: yezz123/setup-uv@v4
    
    - if: inputs.python-version
      name: Configure uv
      shell: bash
      run: echo "UV_SYSTEM_PYTHON=true" >> $GITHUB_ENV

    - if: inputs.python-version && inputs.python-packages
      name: Install Python packages
      shell: bash
      run: uv pip install ${{ inputs.python-packages }}
    
    # Node

    - if: inputs.node-version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - if: inputs.node-version && inputs.npm-packages
      name: Install NPM packages
      shell: bash
      run: npm install -g ${{ inputs.npm-packages }}

    # AWS

    - if: inputs.role-to-assume
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: >
          ${{ inputs.role-to-assume == 'default'
          && 'arn:aws:iam::511603859520:role/prod-objectobject-ca-GitHubActionsCDKRole19D97701-sweSB0Sp33WN'
          || inputs.role-to-assume
          }}
